_wandb:
    value:
        cli_version: 0.22.2
        e:
            9t0ed971ibnclzvl61t68gfvzbnheleu:
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "254931890176"
                        used: "251305209856"
                executable: c:\Users\LENOVO\Documents\Repository\Data And Ai\mlops-project-v2\mlops-project-v2\venv\Scripts\python.exe
                git:
                    commit: bc477dc72855fc97fbd07b19fb32b16ed84de866
                    remote: https://github.com/ramshaintodata/mlops-project-v2.git
                host: DESKTOP-1HG1J2G
                memory:
                    total: "8379490304"
                os: Windows-11-10.0.22631-SP0
                program: ignore
                python: CPython 3.13.7
                root: c:\Users\LENOVO\Documents\Repository\Data And Ai\mlops-project-v2\mlops-project-v2
                startedAt: "2025-11-05T20:25:52.011616Z"
                writerId: 9t0ed971ibnclzvl61t68gfvzbnheleu
        m: []
        python_version: 3.13.7
        t:
            "1":
                - 5
                - 6
                - 53
            "2":
                - 5
                - 6
                - 53
            "3":
                - 2
                - 14
            "4": 3.13.7
            "5": 0.22.2
            "8":
                - 1
                - 3
            "12": 0.22.2
            "13": windows-amd64
C:
    value: 0.0010798145516025582
l1_ratio:
    value: 0.8453226524568394
max_iter:
    value: 100
penalty:
    value: elasticnet
solver:
    value: saga
